version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "TeamName=\"G15\" Environment=\"hackathon\" AiBackend=\"bedrock\" AiModelId=\"anthropic.claude-sonnet-4-5-20250929-v1:0\" StorageBucket=\"w7-hackathon-docs-2\" UserstoreBackend=\"dynamodb\" UserstoreTable=\"\" VectorBackend=\"bedrock_kb\" VectorBedrockKbId=\"U39LHZBJUL\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
